//-----------------------------------------------------------------------------
// @file: tb_pixel_line_buff.sv
//
// @brief: SystemVerilog testbench for pixel_line_buff (VHDL DUT).
// Load in test vector generated by line_buff_sim.mlx for simulating inputs   
// and comparing output. 
//-----------------------------------------------------------------------------
`timescale 1ns / 1ps

import pkg_edge_detection::*;

module tb_pixel_line_buff;
    //-------------------------------------------------------------------------
    // Parameters 
    //-------------------------------------------------------------------------
    localparam CLK_PERIOD = 3.33; // 250 mhz clock period

    // TB driven 
    logic clk = 1'b0;
    logic rstn = 1'b1;
    logic [COMPONENT_WIDTH_C-1:0 ] grey_pixel = 'b0;
    logic pixel_valid = 1'b0;
    logic [15:0] x = 1'b0;
    logic [15:0] y = 1'b0;

    // DUT driven
    window_flat_t flat_window ;
    logic window_valid ;

    pixel_line_buff_wrap pixel_line_buff_wrap_instance (
        .clk_i(clk),
        .rstn_i(rstn),
        .greyscale_pixel_i(grey_pixel),
        .pixel_valid_i(pixel_valid),
        .x_i(x),
        .y_i(y),
        .window_o(flat_window),
        .window_valid_o(window_valid)
    );

    //-------------------------------------------------------------------------
    // TB variables
    //-------------------------------------------------------------------------

    // clock generation 
    initial clk = 0;
    always #(CLK_PERIOD/2) clk = ~clk;

    //test vector
    int fd;
    string header;
    int gp, pv, x_tv, y_tv; // tv = test vector
    window_t window_exp; // window expected
    window_t window;
    //-------------------------------------------------------------------------
    // Test counters
    //-------------------------------------------------------------------------
    int test_count   = 0;
    int pass_count   = 0;
    int fail_count   = 0;
    int skip_count   = 0;

    //-------------------------------------------------------------------------
    // Helper tasks
    //-------------------------------------------------------------------------

    // Assert check with message
    task check(input logic condition, input string msg);
        test_count++;
        if (condition) begin
            pass_count++;
        end else begin
            fail_count++;
            $error("FAIL [%0d]: %s (time=%0t)", test_count, msg, $time);
        end
    endtask

    // Wait N clock cycles
    task wait_clocks(input int n);
        repeat (n) @(posedge clk);
    endtask


    task automatic reset();
        wait_clocks(1);
        rstn = 1'b0;
        wait_clocks(1);
        rstn = 1'b1;
        wait_clocks(1);
    endtask


    // main
    initial begin
        // set up test vector file
        // Vivado would not allow a relative path, so make sure to change this for your installation 
        fd = $fopen("/home/petalinux/Documents/edge-detection-fpga/matlab_prototypes/pixel_line_buff_test_vector.txt", "r");
        if (fd == 0) $fatal(1, "cannot open test vector");
        void'($fgets(header, fd)); // remove header

        // rest dut
        reset();

        while (!$feof(fd)) begin
            $fscanf(fd, "%d %d %d %d", gp, pv, x_tv, y_tv);
            for (int r = 0; r < WINDOW_SIZE_C; r++) begin
                for (int c = 0; c < WINDOW_SIZE_C; c++) begin
                    void'($fscanf(fd, "%d", window_exp[r][c]));
                end
            end

            grey_pixel = gp;
            pixel_valid = pv;
            x = x_tv - 1; // matlab index start one - BRAM index start at zero
            y = y_tv - 1;

            wait_clocks(1);

            window = unflatten_window(flat_window);
            if (window_valid == 1'b1) begin
                `CHECK_WINDOW_EQ_CNT(window, window_exp, "windows", test_count, pass_count, fail_count)
            end
            else begin
                skip_count++;
            end
        end

        $finish;
    end

endmodule
